
-- Drop previous data if table structure changed
-- Users
INSERT INTO users (id, name, email, phone, password, role) VALUES 
(1, 'Demo User', 'demo@example.com', '9876543210', '$2a$10$vI8aWBnW3fID.ZQ4/zo1G.q1lRps.9cGLcZEiGDMVr5yUP1KUOYTa', 'customer'),
(2, 'Admin User', 'admin@example.com', '9876543210', '$2a$10$vI8aWBnW3fID.ZQ4/zo1G.q1lRps.9cGLcZEiGDMVr5yUP1KUOYTa', 'admin')
ON CONFLICT (id) DO NOTHING;

-- Categories
INSERT INTO categories (name, slug, image_url) VALUES 
('Electronics', 'electronics', 'https://loremflickr.com/400/400/laptop/all'),
('Fashion', 'fashion', 'https://loremflickr.com/400/400/jacket/all'),
('Home & Kitchen', 'home-kitchen', 'https://loremflickr.com/400/400/kitchen/all'),
('Books', 'books', 'https://loremflickr.com/400/400/books/all'),
('Sports', 'sports', 'https://loremflickr.com/400/400/sports/all');

-- Products
INSERT INTO products (name, description, price, mrp, discount_percent, stock, category_id, brand, rating, rating_count) VALUES 
('Samsung Galaxy S23 Ultra', 'Experience the best quality with this premium Samsung Galaxy S23 Ultra from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 124999, 154319, 19, 100, 1, 'Samsung', 4.7, 754),
('Apple MacBook Pro M3', 'Experience the best quality with this premium Apple MacBook Pro M3 from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 169900, 287966, 41, 100, 1, 'Apple', 4.2, 610),
('Sony Alpha 7 IV Camera', 'Experience the best quality with this premium Sony Alpha 7 IV Camera from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 210000, 272727, 23, 100, 1, 'Sony', 4.4, 362),
('LG 55 inch OLED 4K TV', 'Experience the best quality with this premium LG 55 inch OLED 4K TV from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 145000, 290000, 50, 100, 1, 'LG', 4.6, 194),
('Apple iPhone 15 Pro', 'Experience the best quality with this premium Apple iPhone 15 Pro from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 134900, 179866, 25, 100, 1, 'Apple', 4.7, 362),
('Samsung Galaxy Watch 6', 'Experience the best quality with this premium Samsung Galaxy Watch 6 from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 34999, 42681, 18, 100, 1, 'Samsung', 4.6, 183),
('Nike Air Max 270 Sneakers', 'Experience the best quality with this premium Nike Air Max 270 Sneakers from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 12995, 17098, 24, 100, 2, 'Nike', 4.9, 207),
('Adidas Ultraboost Running Shoes', 'Experience the best quality with this premium Adidas Ultraboost Running Shoes from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 15999, 31998, 50, 100, 2, 'Adidas', 4.6, 173),
('Levi Premium Trucker Jacket', 'Experience the best quality with this premium Levi Premium Trucker Jacket from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 4500, 7377, 39, 100, 2, 'Levi', 4.2, 191),
('Puma Esssentials T-Shirt', 'Experience the best quality with this premium Puma Esssentials T-Shirt from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 1299, 1998, 35, 100, 2, 'Puma', 4.5, 160),
('Nike Dri-FIT Shorts', 'Experience the best quality with this premium Nike Dri-FIT Shorts from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 2495, 3118, 20, 100, 2, 'Nike', 4.3, 505),
('Levi 501 Original Jeans', 'Experience the best quality with this premium Levi 501 Original Jeans from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 3299, 5075, 35, 100, 2, 'Levi', 4.7, 290),
('Bosch 7kg Front Load Machine', 'Experience the best quality with this premium Bosch 7kg Front Load Machine from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 32490, 67687, 52, 100, 3, 'Bosch', 4.2, 271),
('Philips Air Fryer XL', 'Experience the best quality with this premium Philips Air Fryer XL from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 8999, 15787, 43, 100, 3, 'Philips', 4.5, 287),
('Prestige 3L Pressure Cooker', 'Experience the best quality with this premium Prestige 3L Pressure Cooker from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 1450, 2685, 46, 100, 3, 'Prestige', 4.4, 570),
('Philips Hue Smart Bulbs', 'Experience the best quality with this premium Philips Hue Smart Bulbs from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 2800, 3783, 26, 100, 3, 'Philips', 4.3, 694),
('Bosch Mixer Grinder 1000W', 'Experience the best quality with this premium Bosch Mixer Grinder 1000W from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 5499, 10782, 49, 100, 3, 'Bosch', 4.3, 612),
('Prestige Gas Stove 3 Burner', 'Experience the best quality with this premium Prestige Gas Stove 3 Burner from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 4200, 5526, 24, 100, 3, 'Prestige', 4.9, 414),
('Atomic Habits', 'Experience the best quality with this premium Atomic Habits from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 499, 941, 47, 100, 4, 'Penguin', 4.2, 482),
('The Psychology of Money', 'Experience the best quality with this premium The Psychology of Money from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 395, 718, 45, 100, 4, 'HarperCollins', 4.3, 122),
('Harry Potter Box Set', 'Experience the best quality with this premium Harry Potter Box Set from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 3499, 4267, 18, 100, 4, 'Scholastic', 4.3, 359),
('Rich Dad Poor Dad', 'Experience the best quality with this premium Rich Dad Poor Dad from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 299, 446, 33, 100, 4, 'Oxford', 4.3, 679),
('The Subtile Art of Not Giving a F', 'Experience the best quality with this premium The Subtile Art of Not Giving a F from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 450, 775, 42, 100, 4, 'HarperCollins', 4.5, 779),
('Deep Work by Cal Newport', 'Experience the best quality with this premium Deep Work by Cal Newport from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 399, 532, 25, 100, 4, 'Penguin', 4.3, 134),
('Yonex Astrox 99 Pro Badminton', 'Experience the best quality with this premium Yonex Astrox 99 Pro Badminton from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 14500, 23015, 37, 100, 5, 'Yonex', 4.5, 577),
('Spalding NBA Official Basketball', 'Experience the best quality with this premium Spalding NBA Official Basketball from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 2800, 3684, 24, 100, 5, 'Spalding', 4.7, 203),
('Nivia True Match Football', 'Experience the best quality with this premium Nivia True Match Football from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 1200, 1764, 32, 100, 5, 'Nivia', 4.7, 233),
('Cosco Tennis Racket', 'Experience the best quality with this premium Cosco Tennis Racket from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 3500, 4729, 26, 100, 5, 'Cosco', 4.1, 759),
('Yonex Mavis 350 Shuttlecocks', 'Experience the best quality with this premium Yonex Mavis 350 Shuttlecocks from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 850, 1250, 32, 100, 5, 'Yonex', 4.1, 807),
('Nivia Dominator Goalkeeper Gloves', 'Experience the best quality with this premium Nivia Dominator Goalkeeper Gloves from our collection. Built to last with absolute maximum durability and verified by FlipKart.', 950, 2065, 54, 100, 5, 'Nivia', 4.5, 291);

-- Images
INSERT INTO product_images (product_id, image_url, is_primary) VALUES 
(1, 'https://loremflickr.com/800/800/smartphone/all', true),
(1, 'https://loremflickr.com/800/800/screen/all', false),
(2, 'https://loremflickr.com/800/800/macbook/all', true),
(2, 'https://loremflickr.com/800/800/keyboard/all', false),
(3, 'https://loremflickr.com/800/800/camera/all', true),
(3, 'https://loremflickr.com/800/800/lens/all', false),
(4, 'https://loremflickr.com/800/800/television/all', true),
(4, 'https://loremflickr.com/800/800/display/all', false),
(5, 'https://loremflickr.com/800/800/iphone/all', true),
(5, 'https://loremflickr.com/800/800/phone/all', false),
(6, 'https://loremflickr.com/800/800/smartwatch/all', true),
(6, 'https://loremflickr.com/800/800/watch/all', false),
(7, 'https://loremflickr.com/800/800/sneakers/all', true),
(7, 'https://loremflickr.com/800/800/nike/all', false),
(8, 'https://loremflickr.com/800/800/shoes/all', true),
(8, 'https://loremflickr.com/800/800/runningshoes/all', false),
(9, 'https://loremflickr.com/800/800/denim/all', true),
(9, 'https://loremflickr.com/800/800/jacket/all', false),
(10, 'https://loremflickr.com/800/800/tshirt/all', true),
(10, 'https://loremflickr.com/800/800/shirt/all', false),
(11, 'https://loremflickr.com/800/800/shorts/all', true),
(11, 'https://loremflickr.com/800/800/athleticshorts/all', false),
(12, 'https://loremflickr.com/800/800/jeans/all', true),
(12, 'https://loremflickr.com/800/800/denim/all', false),
(13, 'https://loremflickr.com/800/800/washingmachine/all', true),
(13, 'https://loremflickr.com/800/800/laundry/all', false),
(14, 'https://loremflickr.com/800/800/airfryer/all', true),
(14, 'https://loremflickr.com/800/800/appliance/all', false),
(15, 'https://loremflickr.com/800/800/cooker/all', true),
(15, 'https://loremflickr.com/800/800/pot/all', false),
(16, 'https://loremflickr.com/800/800/bulb/all', true),
(16, 'https://loremflickr.com/800/800/light/all', false),
(17, 'https://loremflickr.com/800/800/blender/all', true),
(17, 'https://loremflickr.com/800/800/mixer/all', false),
(18, 'https://loremflickr.com/800/800/stove/all', true),
(18, 'https://loremflickr.com/800/800/cooking/all', false),
(19, 'https://loremflickr.com/800/800/book/all', true),
(19, 'https://loremflickr.com/800/800/page/all', false),
(20, 'https://loremflickr.com/800/800/finance/all', true),
(20, 'https://loremflickr.com/800/800/reading/all', false),
(21, 'https://loremflickr.com/800/800/magicbook/all', true),
(21, 'https://loremflickr.com/800/800/novel/all', false),
(22, 'https://loremflickr.com/800/800/business/all', true),
(22, 'https://loremflickr.com/800/800/study/all', false),
(23, 'https://loremflickr.com/800/800/selfhelp/all', true),
(23, 'https://loremflickr.com/800/800/diary/all', false),
(24, 'https://loremflickr.com/800/800/library/all', true),
(24, 'https://loremflickr.com/800/800/textbook/all', false),
(25, 'https://loremflickr.com/800/800/badminton/all', true),
(25, 'https://loremflickr.com/800/800/racket/all', false),
(26, 'https://loremflickr.com/800/800/basketball/all', true),
(26, 'https://loremflickr.com/800/800/hoop/all', false),
(27, 'https://loremflickr.com/800/800/football/all', true),
(27, 'https://loremflickr.com/800/800/soccer/all', false),
(28, 'https://loremflickr.com/800/800/tennis/all', true),
(28, 'https://loremflickr.com/800/800/court/all', false),
(29, 'https://loremflickr.com/800/800/shuttlecock/all', true),
(29, 'https://loremflickr.com/800/800/net/all', false),
(30, 'https://loremflickr.com/800/800/goalkeeper/all', true),
(30, 'https://loremflickr.com/800/800/gloves/all', false);

-- Specifications
INSERT INTO product_specifications (product_id, spec_key, spec_value) VALUES 
(1, 'Condition', 'Brand New in Box'),
(1, 'Shipping Target', 'Verified Express'),
(1, 'Warranty', '1 Year Domestic'),
(2, 'Condition', 'Brand New in Box'),
(2, 'Shipping Target', 'Verified Express'),
(2, 'Warranty', '1 Year Domestic'),
(3, 'Condition', 'Brand New in Box'),
(3, 'Shipping Target', 'Verified Express'),
(3, 'Warranty', '1 Year Domestic'),
(4, 'Condition', 'Brand New in Box'),
(4, 'Shipping Target', 'Verified Express'),
(4, 'Warranty', '1 Year Domestic'),
(5, 'Condition', 'Brand New in Box'),
(5, 'Shipping Target', 'Verified Express'),
(5, 'Warranty', '1 Year Domestic'),
(6, 'Condition', 'Brand New in Box'),
(6, 'Shipping Target', 'Verified Express'),
(6, 'Warranty', '1 Year Domestic'),
(7, 'Condition', 'Brand New in Box'),
(7, 'Shipping Target', 'Verified Express'),
(7, 'Warranty', '1 Year Domestic'),
(8, 'Condition', 'Brand New in Box'),
(8, 'Shipping Target', 'Verified Express'),
(8, 'Warranty', '1 Year Domestic'),
(9, 'Condition', 'Brand New in Box'),
(9, 'Shipping Target', 'Verified Express'),
(9, 'Warranty', '1 Year Domestic'),
(10, 'Condition', 'Brand New in Box'),
(10, 'Shipping Target', 'Verified Express'),
(10, 'Warranty', '1 Year Domestic'),
(11, 'Condition', 'Brand New in Box'),
(11, 'Shipping Target', 'Verified Express'),
(11, 'Warranty', '1 Year Domestic'),
(12, 'Condition', 'Brand New in Box'),
(12, 'Shipping Target', 'Verified Express'),
(12, 'Warranty', '1 Year Domestic'),
(13, 'Condition', 'Brand New in Box'),
(13, 'Shipping Target', 'Verified Express'),
(13, 'Warranty', '1 Year Domestic'),
(14, 'Condition', 'Brand New in Box'),
(14, 'Shipping Target', 'Verified Express'),
(14, 'Warranty', '1 Year Domestic'),
(15, 'Condition', 'Brand New in Box'),
(15, 'Shipping Target', 'Verified Express'),
(15, 'Warranty', '1 Year Domestic'),
(16, 'Condition', 'Brand New in Box'),
(16, 'Shipping Target', 'Verified Express'),
(16, 'Warranty', '1 Year Domestic'),
(17, 'Condition', 'Brand New in Box'),
(17, 'Shipping Target', 'Verified Express'),
(17, 'Warranty', '1 Year Domestic'),
(18, 'Condition', 'Brand New in Box'),
(18, 'Shipping Target', 'Verified Express'),
(18, 'Warranty', '1 Year Domestic'),
(19, 'Condition', 'Brand New in Box'),
(19, 'Shipping Target', 'Verified Express'),
(19, 'Warranty', '1 Year Domestic'),
(20, 'Condition', 'Brand New in Box'),
(20, 'Shipping Target', 'Verified Express'),
(20, 'Warranty', '1 Year Domestic'),
(21, 'Condition', 'Brand New in Box'),
(21, 'Shipping Target', 'Verified Express'),
(21, 'Warranty', '1 Year Domestic'),
(22, 'Condition', 'Brand New in Box'),
(22, 'Shipping Target', 'Verified Express'),
(22, 'Warranty', '1 Year Domestic'),
(23, 'Condition', 'Brand New in Box'),
(23, 'Shipping Target', 'Verified Express'),
(23, 'Warranty', '1 Year Domestic'),
(24, 'Condition', 'Brand New in Box'),
(24, 'Shipping Target', 'Verified Express'),
(24, 'Warranty', '1 Year Domestic'),
(25, 'Condition', 'Brand New in Box'),
(25, 'Shipping Target', 'Verified Express'),
(25, 'Warranty', '1 Year Domestic'),
(26, 'Condition', 'Brand New in Box'),
(26, 'Shipping Target', 'Verified Express'),
(26, 'Warranty', '1 Year Domestic'),
(27, 'Condition', 'Brand New in Box'),
(27, 'Shipping Target', 'Verified Express'),
(27, 'Warranty', '1 Year Domestic'),
(28, 'Condition', 'Brand New in Box'),
(28, 'Shipping Target', 'Verified Express'),
(28, 'Warranty', '1 Year Domestic'),
(29, 'Condition', 'Brand New in Box'),
(29, 'Shipping Target', 'Verified Express'),
(29, 'Warranty', '1 Year Domestic'),
(30, 'Condition', 'Brand New in Box'),
(30, 'Shipping Target', 'Verified Express'),
(30, 'Warranty', '1 Year Domestic');

-- Address
INSERT INTO addresses (user_id, full_name, phone, street, city, state, pincode, is_default) VALUES 
(1, 'Demo User', '9876543210', '123 Main Street', 'Bengaluru', 'Karnataka', '560001', true);
